In [1]:
import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv("D:\\sql\\dataset\\NetFlix.csv")
data

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,genres,description
0,s1,TV Show,3%,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,14-Aug-20,2020,TV-MA,4,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...
1,s10,Movie,1920,Vikram Bhatt,"Rajneesh Duggal, Adah Sharma, Indraneil Sengup...",India,15-Dec-17,2008,TV-MA,143,"Horror Movies, International Movies, Thrillers",An architect and his wife move into a castle t...
2,s100,Movie,3 Heroines,Iman Brotoseno,"Reza Rahadian, Bunga Citra Lestari, Tara Basro...",Indonesia,5-Jan-19,2016,TV-PG,124,"Dramas, International Movies, Sports Movies",Three Indonesian women break records by becomi...
3,s1000,Movie,Blue Mountain State: The Rise of Thadland,Lev L. Spiro,"Alan Ritchson, Darin Brooks, James Cade, Rob R...",United States,1-Mar-16,2016,R,90,Comedies,New NFL star Thad buys his old teammates' belo...
4,s1001,TV Show,Blue Planet II,NaN,David Attenborough,United Kingdom,3-Dec-18,2017,TV-G,1,"British TV Shows, Docuseries, Science & Nature TV",This sequel to the award-winning nature series...
...,...,...,...,...,...,...,...,...,...,...,...,...
7782,s995,TV Show,Blown Away,NaN,NaN,Canada,12-Jul-19,2019,TV-14,1,"International TV Shows, Reality TV",Ten master artists turn up the heat in glassbl...
7783,s996,TV Show,Blue Exorcist,NaN,"Nobuhiko Okamoto, Jun Fukuyama, Kana Hanazawa,...",Japan,1-Sep-20,2017,TV-MA,2,"Anime Series, International TV Shows",Determined to throw off the curse of being Sat...
7784,s997,Movie,Blue Is the Warmest Color,Abdellatif Kechiche,"Léa Seydoux, Adèle Exarchopoulos, Salim Kechio...","France, Belgium, Spain",26-Aug-16,2013,NC-17,180,"Dramas, Independent Movies, International Movies","Determined to fall in love, 15-year-old Adele ..."
7785,s998,Movie,Blue Jasmine,Woody Allen,"Cate Blanchett, Sally Hawkins, Alec Baldwin, L...",United States,8-Mar-19,2013,PG-13,98,"Comedies, Dramas, Independent Movies",The high life leads to high anxiety for a fash...
7786,s999,Movie,Blue Jay,Alex Lehmann,"Sarah Paulson, Mark Duplass, Clu Gulager",United States,6-Dec-16,2016,TV-MA,81,"Dramas, Independent Movies, Romantic Movies",Two former high school sweethearts unexpectedl...

In [3]:
data.isnull().sum()

show_id            0
type               0
title              0
director        2389
cast             718
country          507
date_added        10
release_year       0
rating             7
duration           0
genres             0
description        0
dtype: int64

In [4]:
data['director']=data['director'].fillna('unknown')
data['cast']=data['cast'].fillna('not available')
data['country']=data['country'].fillna('unknown')
data['rating']=data['rating'].fillna('not rated')
data['date_added'] = data['date_added'].fillna(pd.to_datetime(data['release_year'], format='%Y'))

In [5]:
data.isnull().sum()

show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          0
duration        0
genres          0
description     0
dtype: int64

In [6]:
data['date_added'] = pd.to_datetime(data['date_added'], errors='coerce').dt.date

C:\Users\Prashant Raghav\AppData\Local\Temp\ipykernel_5704\1506891714.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  data['date_added'] = pd.to_datetime(data['date_added'], errors='coerce').dt.date

In [7]:
data.sample(5)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,genres,description
6571,s6913,Movie,The Sunshine Makers,Cosmo Feilding-Mellen,not available,United Kingdom,2017-03-09,2015,TV-MA,91,"Documentaries, International Movies",Take a trip and witness the rise and fall of T...
2977,s3679,TV Show,Littlest Pet Shop: A World of Our Own,unknown,"Rhona Rees, Ingrid Nilson, Diana Kaarina, Trav...",United States,2019-02-01,2018,TV-Y7,2,Kids' TV,"In Paw-Tucket, pets of all types form friendsh..."
4466,s5018,TV Show,Pyaar Tune Kya Kiya,unknown,"Meiyang Chang, Surbhi Jyoti",India,2017-06-01,2014,TV-14,3,"International TV Shows, Romantic TV Shows, TV ...",From teen lovers defying social and religious ...
6183,s6564,Movie,The Last Laugh,Greg Pritikin,"Chevy Chase, Richard Dreyfuss, Andie MacDowell...",United States,2019-01-11,2019,TV-MA,99,"Comedies, Dramas","After moving to a retirement home, restless ta..."
5765,s6188,Movie,The Burial of Kojo,"Sam ""Blitz"" Bazawule","Cynthia Dankwa, Ama K. Abebrese, Joseph Otsima...","Ghana, United States",2019-03-31,2018,TV-14,81,"Dramas, Independent Movies, International Movies",When a man is left to die inside an illegal go...

In [8]:
data.to_csv('netflix_cleaned.csv',index=False)